FROM python:3.5

MAINTAINER Ubiwehere

# add viewer files
RUN npm run build:prod
RUN mkdir -p /usr/son-viewer
COPY dist/ /usr/son-viewer/

EXPOSE 8080

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8EC0731023C1F15B \
&& echo "deb http://registry.sonata-nfv.eu:8080 ubuntu-trusty main" | tee -a /etc/apt/sources.list \
&& curl -sL https://deb.nodesource.com/setup_8.x | bin/bash -
RUN apt install -y sonata-cli \
&& apt install -y nodejs
RUN npm install -g http-server

COPY entrypoint.sh /sbin/entrypoint.sh
RUN   chmod 755 /sbin/entrypoint.sh

ENTRYPOINT ["/sbin/entrypoint.sh"]
